'use strict';
define({
    "region": [{
        "countryId": 4,
        "name": "\u57c3\u53ca",
        "enName": "Egypt",
        "spellFirst": "A",
        "intlCode": "0020",
        "intlDomain": "EG",
        "isHot": 0
    }, {
        "countryId": 15,
        "name": "\u5965\u5730\u5229",
        "enName": "Austria",
        "spellFirst": "A",
        "intlCode": "0043",
        "intlDomain": "AT",
        "isHot": 0
    }, {
        "countryId": 25,
        "name": "\u963f\u6839\u5ef7",
        "enName": "Argentina",
        "spellFirst": "A",
        "intlCode": "0054",
        "intlDomain": "AR",
        "isHot": 0
    }, {
        "countryId": 31,
        "name": "\u6fb3\u5927\u5229\u4e9a",
        "enName": "Australia",
        "spellFirst": "A",
        "intlCode": "0061",
        "intlDomain": "AU",
        "isHot": 0
    }, {
        "countryId": 44,
        "name": "\u963f\u5bcc\u6c57",
        "enName": "Afghanistan",
        "spellFirst": "A",
        "intlCode": "0093",
        "intlDomain": "AF",
        "isHot": 0
    }, {
        "countryId": 49,
        "name": "\u963f\u5c14\u53ca\u5229\u4e9a",
        "enName": "Algeria",
        "spellFirst": "A",
        "intlCode": "00213",
        "intlDomain": "DZ",
        "isHot": 0
    }, {
        "countryId": 74,
        "name": "\u5b89\u54e5\u62c9",
        "enName": "Angola",
        "spellFirst": "A",
        "intlCode": "00244",
        "intlDomain": "AO",
        "isHot": 0
    }, {
        "countryId": 78,
        "name": "\u57c3\u585e\u4fc4\u6bd4\u4e9a",
        "enName": "Ethiopia",
        "spellFirst": "A",
        "intlCode": "00251",
        "intlDomain": "ET",
        "isHot": 0
    }, {
        "countryId": 100,
        "name": "\u7231\u5c14\u5170",
        "enName": "Ireland",
        "spellFirst": "A",
        "intlCode": "00353",
        "intlDomain": "IE",
        "isHot": 0
    }, {
        "countryId": 102,
        "name": "\u963f\u5c14\u5df4\u5c3c\u4e9a",
        "enName": "Albania",
        "spellFirst": "A",
        "intlCode": "00355",
        "intlDomain": "AL",
        "isHot": 0
    }, {
        "countryId": 109,
        "name": "\u7231\u6c99\u5c3c\u4e9a",
        "enName": "Estonia",
        "spellFirst": "A",
        "intlCode": "00372",
        "intlDomain": "EE",
        "isHot": 0
    }, {
        "countryId": 113,
        "name": "\u5b89\u9053\u5c14\u5171\u548c\u56fd",
        "enName": "Andorra",
        "spellFirst": "A",
        "intlCode": "00376",
        "intlDomain": "AD",
        "isHot": 0
    }, {
        "countryId": 151,
        "name": "\u6fb3\u95e8",
        "enName": "Macao",
        "spellFirst": "A",
        "intlCode": "00853",
        "intlDomain": "MO",
        "isHot": 0
    }, {
        "countryId": 164,
        "name": "\u963f\u66fc",
        "enName": "Oman",
        "spellFirst": "A",
        "intlCode": "00968",
        "intlDomain": "OM",
        "isHot": 0
    }, {
        "countryId": 165,
        "name": "\u963f\u62c9\u4f2f\u8054\u5408\u914b\u957f\u56fd",
        "enName": "United Arab Emirates",
        "spellFirst": "A",
        "intlCode": "00971",
        "intlDomain": "AE",
        "isHot": 0
    }, {
        "countryId": 173,
        "name": "\u963f\u585e\u62dc\u7586",
        "enName": "Azerbaijan",
        "spellFirst": "A",
        "intlCode": "00994",
        "intlDomain": "AZ",
        "isHot": 0
    }, {
        "countryId": 177,
        "name": "\u5b89\u572d\u62c9\u5c9b",
        "enName": "Anguilla",
        "spellFirst": "A",
        "intlCode": "001264",
        "intlDomain": "AI",
        "isHot": 0
    }, {
        "countryId": 178,
        "name": "\u5b89\u63d0\u74dc\u548c\u5df4\u5e03\u8fbe",
        "enName": "Antigua and Barbuda",
        "spellFirst": "A",
        "intlCode": "001268",
        "intlDomain": "AG",
        "isHot": 0
    }, {
        "countryId": 8,
        "name": "\u6bd4\u5229\u65f6",
        "enName": "Belgium",
        "spellFirst": "B",
        "intlCode": "0032",
        "intlDomain": "BE",
        "isHot": 0
    }, {
        "countryId": 20,
        "name": "\u6ce2\u5170",
        "enName": "Poland",
        "spellFirst": "B",
        "intlCode": "0048",
        "intlDomain": "PL",
        "isHot": 0
    }, {
        "countryId": 22,
        "name": "\u79d8\u9c81",
        "enName": "Peru",
        "spellFirst": "B",
        "intlCode": "0051",
        "intlDomain": "PE",
        "isHot": 0
    }, {
        "countryId": 26,
        "name": "\u5df4\u897f",
        "enName": "Brazil",
        "spellFirst": "B",
        "intlCode": "0055",
        "intlDomain": "BR",
        "isHot": 0
    }, {
        "countryId": 43,
        "name": "\u5df4\u57fa\u65af\u5766",
        "enName": "Pakistan",
        "spellFirst": "B",
        "intlCode": "0092",
        "intlDomain": "PK",
        "isHot": 0
    }, {
        "countryId": 57,
        "name": "\u5e03\u57fa\u7eb3\u6cd5\u7d22",
        "enName": "Burkina-faso",
        "spellFirst": "B",
        "intlCode": "00226",
        "intlDomain": "bf",
        "isHot": 0
    }, {
        "countryId": 60,
        "name": "\u8d1d\u5b81",
        "enName": "Benin",
        "spellFirst": "B",
        "intlCode": "00229",
        "intlDomain": "BJ",
        "isHot": 0
    }, {
        "countryId": 84,
        "name": "\u5e03\u9686\u8fea",
        "enName": "Burundi",
        "spellFirst": "B",
        "intlCode": "00257",
        "intlDomain": "BI",
        "isHot": 0
    }, {
        "countryId": 93,
        "name": "\u535a\u8328\u74e6\u7eb3",
        "enName": "Botswana",
        "spellFirst": "B",
        "intlCode": "00267",
        "intlDomain": "BW",
        "isHot": 0
    }, {
        "countryId": 101,
        "name": "\u51b0\u5c9b",
        "enName": "Iceland",
        "spellFirst": "B",
        "intlCode": "00354",
        "intlDomain": "IS",
        "isHot": 0
    }, {
        "countryId": 106,
        "name": "\u4fdd\u52a0\u5229\u4e9a",
        "enName": "Bulgaria",
        "spellFirst": "B",
        "intlCode": "00359",
        "intlDomain": "BG",
        "isHot": 0
    }, {
        "countryId": 112,
        "name": "\u767d\u4fc4\u7f57\u65af",
        "enName": "Belarus",
        "spellFirst": "B",
        "intlCode": "00375",
        "intlDomain": "BY",
        "isHot": 0
    }, {
        "countryId": 122,
        "name": "\u4f2f\u5229\u5179",
        "enName": "Belize",
        "spellFirst": "B",
        "intlCode": "00501",
        "intlDomain": "BZ",
        "isHot": 0
    }, {
        "countryId": 128,
        "name": "\u5df4\u62ff\u9a6c",
        "enName": "Panama",
        "spellFirst": "B",
        "intlCode": "00507",
        "intlDomain": "PA",
        "isHot": 0
    }, {
        "countryId": 130,
        "name": "\u73bb\u5229\u7ef4\u4e9a",
        "enName": "Bolivia",
        "spellFirst": "B",
        "intlCode": "00591",
        "intlDomain": "BO",
        "isHot": 0
    }, {
        "countryId": 134,
        "name": "\u5df4\u62c9\u572d",
        "enName": "Paraguay",
        "spellFirst": "B",
        "intlCode": "00595",
        "intlDomain": "PY",
        "isHot": 0
    }, {
        "countryId": 141,
        "name": "\u5df4\u5e03\u4e9a\u65b0\u51e0\u5185\u4e9a",
        "enName": "Papua New Cuinea",
        "spellFirst": "B",
        "intlCode": "00675",
        "intlDomain": "pg",
        "isHot": 0
    }, {
        "countryId": 167,
        "name": "\u5df4\u6797",
        "enName": "Bahrain",
        "spellFirst": "B",
        "intlCode": "00973",
        "intlDomain": "BH",
        "isHot": 0
    }, {
        "countryId": 175,
        "name": "\u5df4\u54c8\u9a6c",
        "enName": "Bahamas",
        "spellFirst": "B",
        "intlCode": "001242",
        "intlDomain": "BS",
        "isHot": 0
    }, {
        "countryId": 176,
        "name": "\u5df4\u5df4\u591a\u65af",
        "enName": "Barbados",
        "spellFirst": "B",
        "intlCode": "001246",
        "intlDomain": "BB",
        "isHot": 0
    }, {
        "countryId": 180,
        "name": "\u767e\u6155\u5927\u7fa4\u5c9b",
        "enName": "Bermuda Is.",
        "spellFirst": "B",
        "intlCode": "001441",
        "intlDomain": "BM",
        "isHot": 0
    }, {
        "countryId": 186,
        "name": "\u6ce2\u591a\u9ece\u5404",
        "enName": "Puerto Rico",
        "spellFirst": "B",
        "intlCode": "001787",
        "intlDomain": "PR",
        "isHot": 0
    }, {
        "countryId": 17,
        "name": "\u4e39\u9ea6",
        "enName": "Denmark",
        "spellFirst": "D",
        "intlCode": "0045",
        "intlDomain": "DK",
        "isHot": 0
    }, {
        "countryId": 21,
        "name": "\u5fb7\u56fd",
        "enName": "Germany",
        "spellFirst": "D",
        "intlCode": "0049",
        "intlDomain": "DE",
        "isHot": 0
    }, {
        "countryId": 59,
        "name": "\u591a\u54e5",
        "enName": "Togo",
        "spellFirst": "D",
        "intlCode": "00228",
        "intlDomain": "TG",
        "isHot": 0
    }, {
        "countryId": 190,
        "name": "\u591a\u7c73\u5c3c\u52a0\u5171\u548c\u56fd",
        "enName": "Dominica Rep.",
        "spellFirst": "D",
        "intlCode": "001890",
        "intlDomain": "DO",
        "isHot": 0
    }, {
        "countryId": 3,
        "name": "\u4fc4\u7f57\u65af",
        "enName": "Russia",
        "spellFirst": "E",
        "intlCode": "007",
        "intlDomain": "RU",
        "isHot": 0
    }, {
        "countryId": 132,
        "name": "\u5384\u74dc\u591a\u5c14",
        "enName": "Ecuador",
        "spellFirst": "E",
        "intlCode": "00593",
        "intlDomain": "EC",
        "isHot": 0
    }, {
        "countryId": 9,
        "name": "\u6cd5\u56fd",
        "enName": "France",
        "spellFirst": "F",
        "intlCode": "0033",
        "intlDomain": "FR",
        "isHot": 0
    }, {
        "countryId": 33,
        "name": "\u83f2\u5f8b\u5bbe",
        "enName": "Philippines",
        "spellFirst": "F",
        "intlCode": "0063",
        "intlDomain": "PH",
        "isHot": 0
    }, {
        "countryId": 105,
        "name": "\u82ac\u5170",
        "enName": "Finland",
        "spellFirst": "F",
        "intlCode": "00358",
        "intlDomain": "FI",
        "isHot": 0
    }, {
        "countryId": 133,
        "name": "\u6cd5\u5c5e\u572d\u4e9a\u90a3",
        "enName": "French Guiana",
        "spellFirst": "F",
        "intlCode": "00594",
        "intlDomain": "GF",
        "isHot": 0
    }, {
        "countryId": 144,
        "name": "\u6590\u6d4e",
        "enName": "Fiji",
        "spellFirst": "F",
        "intlCode": "00679",
        "intlDomain": "FJ",
        "isHot": 0
    }, {
        "countryId": 148,
        "name": "\u6cd5\u5c5e\u73bb\u5229\u5c3c\u897f\u4e9a",
        "enName": "French Polynesia",
        "spellFirst": "F",
        "intlCode": "00689",
        "intlDomain": "PF",
        "isHot": 0
    }, {
        "countryId": 24,
        "name": "\u53e4\u5df4",
        "enName": "Cuba",
        "spellFirst": "G",
        "intlCode": "0053",
        "intlDomain": "CU",
        "isHot": 0
    }, {
        "countryId": 28,
        "name": "\u54e5\u4f26\u6bd4\u4e9a",
        "enName": "Colombia",
        "spellFirst": "G",
        "intlCode": "0057",
        "intlDomain": "CO",
        "isHot": 0
    }, {
        "countryId": 52,
        "name": "\u5188\u6bd4\u4e9a",
        "enName": "Gambia",
        "spellFirst": "G",
        "intlCode": "00220",
        "intlDomain": "GM",
        "isHot": 0
    }, {
        "countryId": 72,
        "name": "\u521a\u679c",
        "enName": "Congo",
        "spellFirst": "G",
        "intlCode": "00242",
        "intlDomain": "CG",
        "isHot": 0
    }, {
        "countryId": 127,
        "name": "\u54e5\u65af\u8fbe\u9ece\u52a0",
        "enName": "Costa Rica",
        "spellFirst": "G",
        "intlCode": "00506",
        "intlDomain": "CR",
        "isHot": 0
    }, {
        "countryId": 131,
        "name": "\u572d\u4e9a\u90a3",
        "enName": "Guyana",
        "spellFirst": "G",
        "intlCode": "00592",
        "intlDomain": "GY",
        "isHot": 0
    }, {
        "countryId": 174,
        "name": "\u683c\u9c81\u5409\u4e9a",
        "enName": "Georgia",
        "spellFirst": "G",
        "intlCode": "00995",
        "intlDomain": "GE",
        "isHot": 0
    }, {
        "countryId": 183,
        "name": "\u5173\u5c9b",
        "enName": "Guam",
        "spellFirst": "G",
        "intlCode": "001671",
        "intlDomain": "GU",
        "isHot": 0
    }, {
        "countryId": 187,
        "name": "\u683c\u6797\u7eb3\u8fbe",
        "enName": "Grenada",
        "spellFirst": "G",
        "intlCode": "001809",
        "intlDomain": "GD",
        "isHot": 0
    }, {
        "countryId": 7,
        "name": "\u8377\u5170",
        "enName": "Netherlands",
        "spellFirst": "H",
        "intlCode": "0031",
        "intlDomain": "NL",
        "isHot": 0
    }, {
        "countryId": 38,
        "name": "\u97e9\u56fd",
        "enName": "Korea",
        "spellFirst": "H",
        "intlCode": "0082",
        "intlDomain": "KR",
        "isHot": 0
    }, {
        "countryId": 95,
        "name": "\u54c8\u8428\u514b\u65af\u5766",
        "enName": "Kazakstan",
        "spellFirst": "H",
        "intlCode": "00327",
        "intlDomain": "kz",
        "isHot": 0
    }, {
        "countryId": 125,
        "name": "\u6d2a\u90fd\u62c9\u65af",
        "enName": "Honduras",
        "spellFirst": "H",
        "intlCode": "00504",
        "intlDomain": "HN",
        "isHot": 0
    }, {
        "countryId": 129,
        "name": "\u6d77\u5730",
        "enName": "Haiti",
        "spellFirst": "H",
        "intlCode": "00509",
        "intlDomain": "HT",
        "isHot": 0
    }, {
        "countryId": 1,
        "name": "\u52a0\u62ff\u5927",
        "enName": "Canada",
        "spellFirst": "J",
        "intlCode": "001",
        "intlDomain": "CA",
        "isHot": 0
    }, {
        "countryId": 55,
        "name": "\u51e0\u5185\u4e9a",
        "enName": "Guinea",
        "spellFirst": "J",
        "intlCode": "00224",
        "intlDomain": "GN",
        "isHot": 0
    }, {
        "countryId": 64,
        "name": "\u52a0\u7eb3",
        "enName": "Ghana",
        "spellFirst": "J",
        "intlCode": "00233",
        "intlDomain": "GH",
        "isHot": 0
    }, {
        "countryId": 71,
        "name": "\u52a0\u84ec",
        "enName": "Gabon",
        "spellFirst": "J",
        "intlCode": "00241",
        "intlDomain": "GA",
        "isHot": 0
    }, {
        "countryId": 80,
        "name": "\u5409\u5e03\u63d0",
        "enName": "Djibouti",
        "spellFirst": "J",
        "intlCode": "00253",
        "intlDomain": "DJ",
        "isHot": 0
    }, {
        "countryId": 89,
        "name": "\u6d25\u5df4\u5e03\u97e6",
        "enName": "Zimbabwe",
        "spellFirst": "J",
        "intlCode": "00263",
        "intlDomain": "ZW",
        "isHot": 0
    }, {
        "countryId": 96,
        "name": "\u5409\u5c14\u5409\u65af\u5766",
        "enName": "Kyrgyzstan",
        "spellFirst": "J",
        "intlCode": "00331",
        "intlDomain": "KG",
        "isHot": 0
    }, {
        "countryId": 119,
        "name": "\u6377\u514b",
        "enName": "Czech Republic",
        "spellFirst": "J",
        "intlCode": "00420",
        "intlDomain": "CZ",
        "isHot": 0
    }, {
        "countryId": 152,
        "name": "\u67ec\u57d4\u5be8",
        "enName": "Kampuchea (Cambodia )",
        "spellFirst": "J",
        "intlCode": "00855",
        "intlDomain": "KH",
        "isHot": 0
    }, {
        "countryId": 56,
        "name": "\u79d1\u7279\u8fea\u74e6",
        "enName": "Ivory Coast",
        "spellFirst": "K",
        "intlCode": "00225",
        "intlDomain": "CI",
        "isHot": 0
    }, {
        "countryId": 69,
        "name": "\u5580\u9ea6\u9686",
        "enName": "Cameroon",
        "spellFirst": "K",
        "intlCode": "00237",
        "intlDomain": "CM",
        "isHot": 0
    }, {
        "countryId": 81,
        "name": "\u80af\u5c3c\u4e9a",
        "enName": "Kenya",
        "spellFirst": "K",
        "intlCode": "00254",
        "intlDomain": "KE",
        "isHot": 0
    }, {
        "countryId": 145,
        "name": "\u5e93\u514b\u7fa4\u5c9b",
        "enName": "Cook Is.",
        "spellFirst": "K",
        "intlCode": "00682",
        "intlDomain": "ck",
        "isHot": 0
    }, {
        "countryId": 161,
        "name": "\u79d1\u5a01\u7279",
        "enName": "Kuwait",
        "spellFirst": "K",
        "intlCode": "00965",
        "intlDomain": "KW",
        "isHot": 0
    }, {
        "countryId": 168,
        "name": "\u5361\u5854\u5c14",
        "enName": "Qatar",
        "spellFirst": "K",
        "intlCode": "00974",
        "intlDomain": "QA",
        "isHot": 0
    }, {
        "countryId": 179,
        "name": "\u5f00\u66fc\u7fa4\u5c9b",
        "enName": "Cayman Is.",
        "spellFirst": "K",
        "intlCode": "001345",
        "intlDomain": "KY",
        "isHot": 0
    }, {
        "countryId": 13,
        "name": "\u7f57\u9a6c\u5c3c\u4e9a",
        "enName": "Romania",
        "spellFirst": "L",
        "intlCode": "0040",
        "intlDomain": "RO",
        "isHot": 0
    }, {
        "countryId": 51,
        "name": "\u5229\u6bd4\u4e9a",
        "enName": "Libya",
        "spellFirst": "L",
        "intlCode": "00218",
        "intlDomain": "LY",
        "isHot": 0
    }, {
        "countryId": 62,
        "name": "\u5229\u6bd4\u91cc\u4e9a",
        "enName": "Liberia",
        "spellFirst": "L",
        "intlCode": "00231",
        "intlDomain": "LR",
        "isHot": 0
    }, {
        "countryId": 88,
        "name": "\u7559\u5c3c\u65fa",
        "enName": "Reunion",
        "spellFirst": "L",
        "intlCode": "00262",
        "intlDomain": "",
        "isHot": 0
    }, {
        "countryId": 92,
        "name": "\u83b1\u7d22\u6258",
        "enName": "Lesotho",
        "spellFirst": "L",
        "intlCode": "00266",
        "intlDomain": "LS",
        "isHot": 0
    }, {
        "countryId": 99,
        "name": "\u5362\u68ee\u5821",
        "enName": "Luxembourg",
        "spellFirst": "L",
        "intlCode": "00352",
        "intlDomain": "LU",
        "isHot": 0
    }, {
        "countryId": 107,
        "name": "\u7acb\u9676\u5b9b",
        "enName": "Lithuania",
        "spellFirst": "L",
        "intlCode": "00370",
        "intlDomain": "LT",
        "isHot": 0
    }, {
        "countryId": 108,
        "name": "\u62c9\u8131\u7ef4\u4e9a",
        "enName": "Latvia",
        "spellFirst": "L",
        "intlCode": "00371",
        "intlDomain": "LV",
        "isHot": 0
    }, {
        "countryId": 121,
        "name": "\u5217\u652f\u6566\u58eb\u767b",
        "enName": "Liechtenstein",
        "spellFirst": "L",
        "intlCode": "00423",
        "intlDomain": "LI",
        "isHot": 0
    }, {
        "countryId": 153,
        "name": "\u8001\u631d",
        "enName": "Laos",
        "spellFirst": "L",
        "intlCode": "00856",
        "intlDomain": "la",
        "isHot": 0
    }, {
        "countryId": 2,
        "name": "\u7f8e\u56fd",
        "enName": "United States of America",
        "spellFirst": "M",
        "intlCode": "001",
        "intlDomain": "US",
        "isHot": 1
    }, {
        "countryId": 23,
        "name": "\u58a8\u897f\u54e5",
        "enName": "Mexico",
        "spellFirst": "M",
        "intlCode": "0052",
        "intlDomain": "MX",
        "isHot": 0
    }, {
        "countryId": 30,
        "name": "\u9a6c\u6765\u897f\u4e9a",
        "enName": "Malaysia",
        "spellFirst": "M",
        "intlCode": "0060",
        "intlDomain": "MY",
        "isHot": 0
    }, {
        "countryId": 48,
        "name": "\u6469\u6d1b\u54e5",
        "enName": "Morocco",
        "spellFirst": "M",
        "intlCode": "00212",
        "intlDomain": "MA",
        "isHot": 0
    }, {
        "countryId": 54,
        "name": "\u9a6c\u91cc",
        "enName": "Mali",
        "spellFirst": "M",
        "intlCode": "00223",
        "intlDomain": "ML",
        "isHot": 0
    }, {
        "countryId": 61,
        "name": "\u6bdb\u91cc\u6c42\u65af",
        "enName": "Mauritius",
        "spellFirst": "M",
        "intlCode": "00230",
        "intlDomain": "MU",
        "isHot": 0
    }, {
        "countryId": 85,
        "name": "\u83ab\u6851\u6bd4\u514b",
        "enName": "Mozambique",
        "spellFirst": "M",
        "intlCode": "00258",
        "intlDomain": "MZ",
        "isHot": 0
    }, {
        "countryId": 87,
        "name": "\u9a6c\u8fbe\u52a0\u65af\u52a0",
        "enName": "Madagascar",
        "spellFirst": "M",
        "intlCode": "00261",
        "intlDomain": "MG",
        "isHot": 0
    }, {
        "countryId": 91,
        "name": "\u9a6c\u62c9\u7ef4",
        "enName": "Malawi",
        "spellFirst": "M",
        "intlCode": "00265",
        "intlDomain": "MW",
        "isHot": 0
    }, {
        "countryId": 103,
        "name": "\u9a6c\u8033\u4ed6",
        "enName": "Malta",
        "spellFirst": "M",
        "intlCode": "00356",
        "intlDomain": "MT",
        "isHot": 0
    }, {
        "countryId": 110,
        "name": "\u6469\u5c14\u591a\u74e6",
        "enName": "Moldova, Republic of",
        "spellFirst": "M",
        "intlCode": "00373",
        "intlDomain": "MD",
        "isHot": 0
    }, {
        "countryId": 114,
        "name": "\u6469\u7eb3\u54e5",
        "enName": "Monaco",
        "spellFirst": "M",
        "intlCode": "00377",
        "intlDomain": "MC",
        "isHot": 0
    }, {
        "countryId": 135,
        "name": "\u9a6c\u63d0\u5c3c\u514b",
        "enName": "Martinique",
        "spellFirst": "M",
        "intlCode": "00596",
        "intlDomain": "MQ",
        "isHot": 0
    }, {
        "countryId": 154,
        "name": "\u5b5f\u52a0\u62c9\u56fd",
        "enName": "Bangladesh",
        "spellFirst": "M",
        "intlCode": "00880",
        "intlDomain": "BD",
        "isHot": 0
    }, {
        "countryId": 156,
        "name": "\u9a6c\u5c14\u4ee3\u592b",
        "enName": "Maldives",
        "spellFirst": "M",
        "intlCode": "00960",
        "intlDomain": "MV",
        "isHot": 0
    }, {
        "countryId": 169,
        "name": "\u8499\u53e4",
        "enName": "Mongolia",
        "spellFirst": "M",
        "intlCode": "00976",
        "intlDomain": "MN",
        "isHot": 0
    }, {
        "countryId": 181,
        "name": "\u8499\u7279\u585e\u62c9\u7279\u5c9b",
        "enName": "Montserrat Is",
        "spellFirst": "M",
        "intlCode": "001664",
        "intlDomain": "MS",
        "isHot": 0
    }, {
        "countryId": 5,
        "name": "\u5357\u975e",
        "enName": "South Africa",
        "spellFirst": "N",
        "intlCode": "0027",
        "intlDomain": "ZA",
        "isHot": 0
    }, {
        "countryId": 19,
        "name": "\u632a\u5a01",
        "enName": "Norway",
        "spellFirst": "N",
        "intlCode": "0047",
        "intlDomain": "NO",
        "isHot": 0
    }, {
        "countryId": 58,
        "name": "\u5c3c\u65e5\u5c14",
        "enName": "Niger",
        "spellFirst": "N",
        "intlCode": "00227",
        "intlDomain": "NE",
        "isHot": 0
    }, {
        "countryId": 66,
        "name": "\u5c3c\u65e5\u5229\u4e9a",
        "enName": "Nigeria",
        "spellFirst": "N",
        "intlCode": "00234",
        "intlDomain": "NG",
        "isHot": 0
    }, {
        "countryId": 90,
        "name": "\u7eb3\u7c73\u6bd4\u4e9a",
        "enName": "Namibia",
        "spellFirst": "N",
        "intlCode": "00264",
        "intlDomain": "NA",
        "isHot": 0
    }, {
        "countryId": 126,
        "name": "\u5c3c\u52a0\u62c9\u74dc",
        "enName": "Nicaragua",
        "spellFirst": "N",
        "intlCode": "00505",
        "intlDomain": "NI",
        "isHot": 0
    }, {
        "countryId": 157,
        "name": "\u9ece\u5df4\u5ae9",
        "enName": "Lebanon",
        "spellFirst": "N",
        "intlCode": "00961",
        "intlDomain": "LB",
        "isHot": 0
    }, {
        "countryId": 170,
        "name": "\u5c3c\u6cca\u5c14",
        "enName": "Nepal",
        "spellFirst": "N",
        "intlCode": "00977",
        "intlDomain": "NP",
        "isHot": 0
    }, {
        "countryId": 98,
        "name": "\u8461\u8404\u7259",
        "enName": "Portugal",
        "spellFirst": "P",
        "intlCode": "00351",
        "intlDomain": "PT",
        "isHot": 0
    }, {
        "countryId": 14,
        "name": "\u745e\u58eb",
        "enName": "Switzerland",
        "spellFirst": "R",
        "intlCode": "0041",
        "intlDomain": "CH",
        "isHot": 0
    }, {
        "countryId": 18,
        "name": "\u745e\u5178",
        "enName": "Sweden",
        "spellFirst": "R",
        "intlCode": "0046",
        "intlDomain": "SE",
        "isHot": 0
    }, {
        "countryId": 37,
        "name": "\u65e5\u672c",
        "enName": "Japan",
        "spellFirst": "R",
        "intlCode": "0081",
        "intlDomain": "JP",
        "isHot": 1
    }, {
        "countryId": 45,
        "name": "\u65af\u91cc\u5170\u5361",
        "enName": "Sri Lanka",
        "spellFirst": "S",
        "intlCode": "0094",
        "intlDomain": "LK",
        "isHot": 0
    }, {
        "countryId": 53,
        "name": "\u585e\u5185\u52a0\u5c14",
        "enName": "Senegal",
        "spellFirst": "S",
        "intlCode": "00221",
        "intlDomain": "SN",
        "isHot": 0
    }, {
        "countryId": 63,
        "name": "\u585e\u62c9\u5229\u6602",
        "enName": "Sierra Leone",
        "spellFirst": "S",
        "intlCode": "00232",
        "intlDomain": "SL",
        "isHot": 0
    }, {
        "countryId": 70,
        "name": "\u5723\u591a\u7f8e\u548c\u666e\u6797\u897f\u6bd4",
        "enName": "Sao Tome and Principe",
        "spellFirst": "S",
        "intlCode": "00239",
        "intlDomain": "ST",
        "isHot": 0
    }, {
        "countryId": 76,
        "name": "\u585e\u820c\u5c14",
        "enName": "Seychelles",
        "spellFirst": "S",
        "intlCode": "00248",
        "intlDomain": "SC",
        "isHot": 0
    }, {
        "countryId": 77,
        "name": "\u82cf\u4e39",
        "enName": "Sudan",
        "spellFirst": "S",
        "intlCode": "00249",
        "intlDomain": "SD",
        "isHot": 0
    }, {
        "countryId": 79,
        "name": "\u7d22\u9a6c\u91cc",
        "enName": "Somali",
        "spellFirst": "S",
        "intlCode": "00252",
        "intlDomain": "SO",
        "isHot": 0
    }, {
        "countryId": 104,
        "name": "\u585e\u6d66\u8def\u65af",
        "enName": "Cyprus",
        "spellFirst": "S",
        "intlCode": "00357",
        "intlDomain": "CY",
        "isHot": 0
    }, {
        "countryId": 118,
        "name": "\u65af\u6d1b\u6587\u5c3c\u4e9a",
        "enName": "Slovenia",
        "spellFirst": "S",
        "intlCode": "00386",
        "intlDomain": "SI",
        "isHot": 0
    }, {
        "countryId": 120,
        "name": "\u65af\u6d1b\u4f10\u514b",
        "enName": "Slovakia",
        "spellFirst": "S",
        "intlCode": "00421",
        "intlDomain": "SK",
        "isHot": 0
    }, {
        "countryId": 124,
        "name": "\u8428\u5c14\u74e6\u591a",
        "enName": "EI Salvador",
        "spellFirst": "S",
        "intlCode": "00503",
        "intlDomain": "sv",
        "isHot": 0
    }, {
        "countryId": 136,
        "name": "\u82cf\u91cc\u5357",
        "enName": "Suriname",
        "spellFirst": "S",
        "intlCode": "00597",
        "intlDomain": "SR",
        "isHot": 0
    }, {
        "countryId": 143,
        "name": "\u6240\u7f57\u95e8\u7fa4\u5c9b",
        "enName": "Solomon Is",
        "spellFirst": "S",
        "intlCode": "00677",
        "intlDomain": "SB",
        "isHot": 0
    }, {
        "countryId": 162,
        "name": "\u6c99\u7279\u963f\u62c9\u4f2f",
        "enName": "Saudi Arabia",
        "spellFirst": "S",
        "intlCode": "00966",
        "intlDomain": "SA",
        "isHot": 0
    }, {
        "countryId": 36,
        "name": "\u6cf0\u56fd",
        "enName": "Thailand",
        "spellFirst": "T",
        "intlCode": "0066",
        "intlDomain": "TH",
        "isHot": 0
    }, {
        "countryId": 41,
        "name": "\u571f\u8033\u5176",
        "enName": "Turkey",
        "spellFirst": "T",
        "intlCode": "0090",
        "intlDomain": "TR",
        "isHot": 0
    }, {
        "countryId": 50,
        "name": "\u7a81\u5c3c\u65af",
        "enName": "Tunisia",
        "spellFirst": "T",
        "intlCode": "00216",
        "intlDomain": "TN",
        "isHot": 0
    }, {
        "countryId": 82,
        "name": "\u5766\u6851\u5c3c\u4e9a",
        "enName": "Tanzania",
        "spellFirst": "T",
        "intlCode": "00255",
        "intlDomain": "TZ",
        "isHot": 0
    }, {
        "countryId": 142,
        "name": "\u6c64\u52a0",
        "enName": "Tonga",
        "spellFirst": "T",
        "intlCode": "00676",
        "intlDomain": "TO",
        "isHot": 0
    }, {
        "countryId": 155,
        "name": "\u53f0\u6e7e\u7701",
        "enName": "Taiwan",
        "spellFirst": "T",
        "intlCode": "00886",
        "intlDomain": "TW",
        "isHot": 1
    }, {
        "countryId": 171,
        "name": "\u5854\u5409\u514b\u65af\u5766",
        "enName": "Tajikstan",
        "spellFirst": "T",
        "intlCode": "00992",
        "intlDomain": "tj",
        "isHot": 0
    }, {
        "countryId": 172,
        "name": "\u571f\u5e93\u66fc\u65af\u5766",
        "enName": "Turkmenistan",
        "spellFirst": "T",
        "intlCode": "00993",
        "intlDomain": "TM",
        "isHot": 0
    }, {
        "countryId": 188,
        "name": "\u7279\u7acb\u5c3c\u8fbe\u548c\u591a\u5df4\u54e5",
        "enName": "Trinidad and Tobago",
        "spellFirst": "T",
        "intlCode": "001809",
        "intlDomain": "TT",
        "isHot": 0
    }, {
        "countryId": 29,
        "name": "\u59d4\u5185\u745e\u62c9",
        "enName": "Venezuela",
        "spellFirst": "W",
        "intlCode": "0058",
        "intlDomain": "VE",
        "isHot": 0
    }, {
        "countryId": 65,
        "name": "\u4e4c\u5179\u522b\u514b\u65af\u5766",
        "enName": "Uzbekistan",
        "spellFirst": "W",
        "intlCode": "00998",
        "intlDomain": "UZ",
        "isHot": 0
    }, {
        "countryId": 83,
        "name": "\u4e4c\u5e72\u8fbe",
        "enName": "Uganda",
        "spellFirst": "W",
        "intlCode": "00256",
        "intlDomain": "UG",
        "isHot": 0
    }, {
        "countryId": 116,
        "name": "\u4e4c\u514b\u5170",
        "enName": "Ukraine",
        "spellFirst": "W",
        "intlCode": "00380",
        "intlDomain": "UA",
        "isHot": 0
    }, {
        "countryId": 123,
        "name": "\u5371\u5730\u9a6c\u62c9",
        "enName": "Guatemala",
        "spellFirst": "W",
        "intlCode": "00502",
        "intlDomain": "GT",
        "isHot": 0
    }, {
        "countryId": 137,
        "name": "\u4e4c\u62c9\u572d",
        "enName": "Uruguay",
        "spellFirst": "W",
        "intlCode": "00598",
        "intlDomain": "UY",
        "isHot": 0
    }, {
        "countryId": 139,
        "name": "\u6587\u83b1",
        "enName": "Brunei",
        "spellFirst": "W",
        "intlCode": "00673",
        "intlDomain": "BN",
        "isHot": 0
    }, {
        "countryId": 6,
        "name": "\u5e0c\u814a",
        "enName": "Greece",
        "spellFirst": "X",
        "intlCode": "0030",
        "intlDomain": "GR",
        "isHot": 0
    }, {
        "countryId": 10,
        "name": "\u897f\u73ed\u7259",
        "enName": "Spain",
        "spellFirst": "X",
        "intlCode": "0034",
        "intlDomain": "ES",
        "isHot": 0
    }, {
        "countryId": 11,
        "name": "\u5308\u7259\u5229",
        "enName": "Hungary",
        "spellFirst": "X",
        "intlCode": "0036",
        "intlDomain": "HU",
        "isHot": 0
    }, {
        "countryId": 34,
        "name": "\u65b0\u897f\u5170",
        "enName": "New Zealand",
        "spellFirst": "X",
        "intlCode": "0064",
        "intlDomain": "NZ",
        "isHot": 0
    }, {
        "countryId": 35,
        "name": "\u65b0\u52a0\u5761",
        "enName": "Singapore",
        "spellFirst": "X",
        "intlCode": "0065",
        "intlDomain": "SG",
        "isHot": 0
    }, {
        "countryId": 150,
        "name": "\u9999\u6e2f",
        "enName": "Hongkong",
        "spellFirst": "X",
        "intlCode": "00852",
        "intlDomain": "HK",
        "isHot": 1
    }, {
        "countryId": 159,
        "name": "\u53d9\u5229\u4e9a",
        "enName": "Syria",
        "spellFirst": "X",
        "intlCode": "00963",
        "intlDomain": "SY",
        "isHot": 0
    }, {
        "countryId": 12,
        "name": "\u610f\u5927\u5229",
        "enName": "Italy",
        "spellFirst": "Y",
        "intlCode": "0039",
        "intlDomain": "IT",
        "isHot": 0
    }, {
        "countryId": 16,
        "name": "\u82f1\u56fd",
        "enName": "United Kiongdom",
        "spellFirst": "Y",
        "intlCode": "0044",
        "intlDomain": "GB",
        "isHot": 0
    }, {
        "countryId": 32,
        "name": "\u5370\u5ea6\u5c3c\u897f\u4e9a",
        "enName": "Indonesia",
        "spellFirst": "Y",
        "intlCode": "0062",
        "intlDomain": "ID",
        "isHot": 0
    }, {
        "countryId": 39,
        "name": "\u8d8a\u5357",
        "enName": "Vietnam",
        "spellFirst": "Y",
        "intlCode": "0084",
        "intlDomain": "VN",
        "isHot": 0
    }, {
        "countryId": 42,
        "name": "\u5370\u5ea6",
        "enName": "India",
        "spellFirst": "Y",
        "intlCode": "0091",
        "intlDomain": "IN",
        "isHot": 1
    }, {
        "countryId": 47,
        "name": "\u4f0a\u6717",
        "enName": "Iran",
        "spellFirst": "Y",
        "intlCode": "0098",
        "intlDomain": "IR",
        "isHot": 0
    }, {
        "countryId": 111,
        "name": "\u4e9a\u7f8e\u5c3c\u4e9a",
        "enName": "Armenia",
        "spellFirst": "Y",
        "intlCode": "00374",
        "intlDomain": "AM",
        "isHot": 0
    }, {
        "countryId": 158,
        "name": "\u7ea6\u65e6",
        "enName": "Jordan",
        "spellFirst": "Y",
        "intlCode": "00962",
        "intlDomain": "JO",
        "isHot": 0
    }, {
        "countryId": 160,
        "name": "\u4f0a\u62c9\u514b",
        "enName": "Iraq",
        "spellFirst": "Y",
        "intlCode": "00964",
        "intlDomain": "IQ",
        "isHot": 0
    }, {
        "countryId": 163,
        "name": "\u4e5f\u95e8",
        "enName": "Yemen",
        "spellFirst": "Y",
        "intlCode": "00967",
        "intlDomain": "YE",
        "isHot": 0
    }, {
        "countryId": 166,
        "name": "\u4ee5\u8272\u5217",
        "enName": "Israel",
        "spellFirst": "Y",
        "intlCode": "00972",
        "intlDomain": "IL",
        "isHot": 0
    }, {
        "countryId": 189,
        "name": "\u7259\u4e70\u52a0",
        "enName": "Jamaica",
        "spellFirst": "Y",
        "intlCode": "001876",
        "intlDomain": "JM",
        "isHot": 0
    }, {
        "countryId": 27,
        "name": "\u667a\u5229",
        "enName": "Chile",
        "spellFirst": "Z",
        "intlCode": "0056",
        "intlDomain": "CL",
        "isHot": 0
    }, {
        "countryId": 40,
        "name": "\u4e2d\u56fd",
        "enName": "China",
        "spellFirst": "Z",
        "intlCode": "0086",
        "intlDomain": "CN",
        "isHot": 1
    }, {
        "countryId": 67,
        "name": "\u4e4d\u5f97",
        "enName": "Chad",
        "spellFirst": "Z",
        "intlCode": "00235",
        "intlDomain": "TD",
        "isHot": 0
    }, {
        "countryId": 68,
        "name": "\u4e2d\u975e\u5171\u548c\u56fd",
        "enName": "Central African Republic",
        "spellFirst": "Z",
        "intlCode": "00236",
        "intlDomain": "CF",
        "isHot": 0
    }, {
        "countryId": 86,
        "name": "\u8d5e\u6bd4\u4e9a",
        "enName": "Zambia",
        "spellFirst": "Z",
        "intlCode": "00260",
        "intlDomain": "ZM",
        "isHot": 0
    }, {
        "countryId": 97,
        "name": "\u76f4\u5e03\u7f57\u9640",
        "enName": "Gibraltar",
        "spellFirst": "Z",
        "intlCode": "00350",
        "intlDomain": "GI",
        "isHot": 0
    }]
});